library(tidyverse)
library(ggplot2)

us_census_data <- read.csv('Data/us_census_name_2010/surnames_appearing_more_than_100_times/Names_2010Census.csv')

vietnamese_surname_list <- c(
  'An',
  'Bach',
  'Banh',
  'Bui', 
  'Buu',
  'Cao', 
  'Chu',
  'Chung',
  'Dam', 
  'Dang', 
  'Dao', 
  'Diep', 
  'Dinh', 
  'Do', 
  'Doan', 
  'Duong', 
  'Giang', 
  'Hoa',
  'Hoang',
  'Huynh', 
  'Kieu',
  'La', 
  'Le',
  'Luc',
  'Luong', 
  'Luu',
  'Lieu',
  'Ly',
  'Mai', 
  'Ma',
  'Mach',
  'Nghiem',
  'Ngo',
  'Nguyen', 
  'Phi',
  'Pham', 
  'Phan', 
  'Phu',
  'Phung', 
  'Quach', 
  'Quang', 
  'To',
  'Ta',
  'Thach', 
  'Sai',
  'Thai', 
  'Thanh', 
  'Thi', 
  'Tieu', 
  'Tong',
  'Ton', 
  'Tran',
  'Trang', 
  'Trieu', 
  'Trinh', 
  'Truong', 
  'Van', 
  'Vinh',
  'Vo',
  'Vong', 
  'Vu',
  'Vuong' 
)

vietnamese_american_data <- us_census_data %>% filter(name %in% toupper(vietnamese_surname_list)) 
write.csv(vietnamese_american_data, 'Data/Vietnam (US 2010)/vietnamese_american_data.csv', row.names = FALSE)
